---
- name: Get wuauserv start_mode
  ansible.windows.win_service:
    name: wuauserv
  register: wuauserv_state
  
- debug:
    var: wuauserv_state.start_mode

- name: Set wuauserv start_mode=manual
  ansible.windows.win_service:
    name: wuauserv
    start_mode: manual
  register: wuauserv_state_modified
  when: wuauserv_state.start_mode == 'disabled'

  

# tasks file for ansible-role-win-dotnet35
- name: Download Windows Server ISO
  win_get_url:
    url: '{{ windows_server_iso_url }}'
    dest: C:\Windows\Temp\windows_server.iso
    force: no

- name: Sleep for 2 seconds and continue with play
  wait_for:
    timeout: 2
  delegate_to: localhost

- name: Mount Windows Server ISO
  win_disk_image:
    image_path: C:\Windows\Temp\windows_server.iso
    state: present
  register: disk_image_out

- name: Sleep for 2 seconds and continue with play
  wait_for:
    timeout: 2
  delegate_to: localhost

# mount_paths[] !!!

- name: Install Net-Framework-Core Features (ansible < 2.10)
  win_feature:
    name: Net-Framework-Core
    source: '{{ disk_image_out.mount_path }}sources\sxs'
    state: present
  when: ansible_version.full is version_compare('2.10', '<') 

- name: Install Net-Framework-Core Features (ansible >= 2.10)
  win_feature:
    name: Net-Framework-Core
    source: '{{ disk_image_out.mount_paths[0] }}sources\sxs'
    state: present
  when: ansible_version.full is version_compare('2.10', '>=')

- name: Umount Windows Server ISO
  win_disk_image:
    image_path: C:\Windows\Temp\windows_server.iso
    state: absent

- name: Restore wuauserv start_mode={{ wuauserv_state.start_mode }}
  ansible.windows.win_service:
    name: wuauserv
    start_mode: '{{ wuauserv_state.start_mode }}'
  when: wuauserv_state_modified.changed